# syntax=docker/dockerfile:1
#Which "official Java image" ?
FROM openjdk:20-ea-17-jdk-oracle
#working directory
WORKDIR /app
#copy from your Host(PC, laptop) to container
COPY employee-service/.mvn/ .mvn
COPY employee-service/mvnw employee-service/pom.xml ./
#Run this inside the image
#RUN ./mvnw dependency:go-offline
COPY employee-service/src ./src
#run inside container
CMD ["./mvnw", "clean"]
CMD ["./mvnw", "spring-boot:run"]