# syntax=docker/dockerfile:1
#Which "official Java image" ?
FROM openjdk:20-ea-17-jdk-oracle
#working directory
WORKDIR /app
#copy from your Host(PC, laptop) to container
COPY api-gateway/.mvn/ .mvn
COPY api-gateway/mvnw api-gateway/pom.xml ./
#Run this inside the image
#RUN ./mvnw dependency:go-offline
COPY api-gateway/src ./src
#run inside container
CMD ["./mvnw", "clean"]
CMD ["./mvnw", "spring-boot:run"]