
# Use Node 18.14.1 as the base image
FROM node:18.14.1

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY react-frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the app files to the working directory
COPY react-frontend/. .

# Build the React app
RUN npm run build

# Set the command to start the app
CMD [ "npm", "start" ]